name: Test deployment

on:
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test build and artifact upload
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 21.4.0
      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
